language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - GCLOUD_SDK_DIR=$HOME/google-cloud-sdk
    - GCLOUD_PROJECT=mymovies-7e138
    - GCLOUD_KEY_FILE=gcloudkey.json

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $GCLOUD_SDK_DIR

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

before_install:
  # see https://github.com/travis-ci/travis-ci/issues/8874#issuecomment-350350607
  - yes | sdkmanager "platforms;android-27"
  - curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-182.0.0-linux-x86_64.tar.gz -o gcloud.tar.gz
  - tar xzf gcloud.tar.gz -C $HOME
  - $GCLOUD_SDK_DIR/install.sh --quiet --usage-reporting false
  - source $GCLOUD_SDK_DIR/path.bash.inc

  # Decrypt the key file
  - openssl aes-256-cbc -K $encrypted_10a1dc9634f9_key -iv $encrypted_10a1dc9634f9_iv
    -in "$GCLOUD_KEY_FILE.enc" -out $GCLOUD_KEY_FILE -d

  - gcloud config set project $GCLOUD_PROJECT
  - gcloud auth activate-service-account --key-file=$GCLOUD_KEY_FILE


jobs:
  include:
    - stage: test
      script:
        - ./ci/test.sh
    - stage: smoketest
      if: type = pull_request
      script:
        - gcloud -v
        - ./ci/run-test-matrix.sh smoketest
    - stage: roadtest
      if: branch = master and type != pull_request
      script:
        - ./ci/run-test-matrix.sh roadtest
