language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - GCLOUD_SDK_DIR=$HOME/google-cloud-sdk
    - GCLOUD_PROJECT=mymovies-7e138
    - GCLOUD_KEY_FILE=gcloudkey.json

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $GCLOUD_SDK_DIR

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27

before_install:
  # see https://github.com/travis-ci/travis-ci/issues/8874#issuecomment-350350607
  - yes | sdkmanager "platforms;android-27"

jobs:
  include:
    - stage: test
      script:
        - ./ci/test.sh
    - stage: smoketest
      if: type = pull_request
      script:
        - ./ci/setup-gcloud.sh
        - ./ci/run-test-matrix.sh smoketest
    - stage: roadtest
      if: branch = master and type != pull_request
      script:
        - ./ci/setup-gcloud.sh
        - ./ci/run-test-matrix.sh roadtest
